_BASE_: "../e2e_mask_rcnn_R_50_FPN_2x_gn.yaml"
MODEL:
  WEIGHT: "catalog://Caffe2Detectron/COCO/48616381/e2e_mask_rcnn_R-50-FPN_2x_gn"
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 40.32, 0.02], ["segm", "AP", 35.68, 0.02]]
