_BASE_: "../e2e_mask_rcnn_X_101_32x8d_FPN_1x.yaml"
INPUT:
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]  # Default in Detectron v1
MODEL:
  WEIGHT: "catalog://Caffe2Detectron/COCO/36761843/e2e_mask_rcnn_X-101-32x8d-FPN_1x"
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 42.012, 0.05], ["segm", "AP", 37.276, 0.05]]
