MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/private/home/fmassa/model_final_faster_rcnn.pkl"
  C2_COMPAT:
    WEIGHT_LOADER: "faster_rcnn_R_50_C4"
DATASETS:
  TEST: ("coco_2014_minival",)
