_BASE_: "../e2e_mask_rcnn_R_50_C4_1x.yaml"
MODEL:
  WEIGHT: "catalog://Caffe2Detectron/COCO/35858791/e2e_mask_rcnn_R-50-C4_1x"
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 35.80, 0.05], ["segm", "AP", 31.34, 0.05]]
