MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/private/home/fmassa/detectron_c2_models/e2e_mask_rcnn_R_50_C4_1x.pkl"
  C2_COMPAT:
    WEIGHT_LOADER: "mask_rcnn_R_50_C4"
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True
  MASK_ON: True
DATASETS:
  TEST: ("coco_2014_minival",)
