_BASE_: "../rpn_R_50_C4_1x.yaml"
INPUT:
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]  # Default in Detectron v1
MODEL:
  WEIGHT: "catalog://Caffe2Detectron/COCO/35998355/rpn_R-50-C4_1x"
TEST:
  EXPECTED_RESULTS: [["box_proposals", "AR@1000", 51.70, 0.02]]
