_BASE_: "../Base-FPN.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  KEYPOINT_ON: True
DATASETS:
  TRAIN: ("keypoints_coco_2014_minival_100",)
  TEST: ("keypoints_coco_2014_minival_100",)
SOLVER:
  BASE_LR: 0.02
  STEPS: (30,)
  MAX_ITER: 40
