_BASE_: "../Base-C4.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2014_minival_100",)
  TEST: ("coco_2014_minival_100",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (30,)
  MAX_ITER: 40
  IMS_PER_BATCH: 8
