_BASE_: "../e2e_mask_rcnn_R_50_C4_1x.yaml"
MODEL:
  # f111802010
  WEIGHT: "/mnt/vol/gfsai-bistro-east/ai-group/bistro/gpu/rbg/20190430/baseline_2b13c3d25abc_rm_plus_one_final_V100/e2e_mask_rcnn_R_50_C4_1x.yaml.20_16_32.6E7oaljq/output/model_final.pth"
DATASETS:
  TEST: ("coco_2014_minival_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 44.82, 0.02], ["segm", "AP", 39.44, 0.02]]
