_BASE_: "../e2e_mask_rcnn_R_50_DC5_1x.yaml"
MODEL:
  # f111802619
  WEIGHT: "/mnt/vol/gfsai-bistro-east/ai-group/bistro/gpu/rbg/20190430/baseline_2b13c3d25abc_rm_plus_one_final_V100/e2e_mask_rcnn_R_50_DC5_1x.yaml.20_22_50.bqGtGvq6/output/model_final.pth"
DATASETS:
  TEST: ("coco_2014_minival_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 46.50, 0.02], ["segm", "AP", 40.54, 0.02]]
