_BASE_: "../e2e_mask_rcnn_R_50_C4_1x.yaml"
INPUT:
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]  # Default in Detectron v1
MODEL:
  WEIGHT: "catalog://Caffe2Detectron/COCO/35858791/e2e_mask_rcnn_R-50-C4_1x"
DATASETS:
  TEST: ("coco_2014_minival_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 43.158, 0.02], ["segm", "AP", 38.755, 0.02]]
