_BASE_: "../e2e_mask_rcnn_R_50_C4_1x.yaml"
MODEL:
  WEIGHT: "catalog://Caffe2Detectron/COCO/35858791/e2e_mask_rcnn_R-50-C4_1x"
DATASETS:
  TEST: ("coco_2014_minival_100",)
TEST:
  IMS_PER_BATCH: 6  # ok for 2 GPUs each with 12GB memory
  EXPECTED_RESULTS: [["bbox", "AP", 43.4214, 0.01], ["segm", "AP", 38.7128, 0.01]]
