_BASE_: "../Base-FPN.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
  KEYPOINT_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 2
  ROI_KEYPOINT_HEAD:
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 56
DATASETS:
  TRAIN: ("keypoints_coco_2014_minival",)
  TEST: ("keypoints_coco_2014_minival",)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  WARMUP_ITERS: 100
  STEPS: (5500, 5800)
  MAX_ITER: 6000
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 55.05, 0.7], ["keypoints", "AP", 76.42, 0.7]]
