_BASE_: "../e2e_mask_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHT: "detectron2://e2e_mask_rcnn_R_50_FPN_1x/111801949/model_final_05dc3b6ea7b1da199fafd3b58defdaae.pkl"
DATASETS:
  TEST: ("coco_2014_minival_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 43.51, 0.02], ["segm", "AP",  40.46, 0.02]]
