_BASE_: "../Base-C4.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2014_minival",)
  TEST: ("coco_2014_minival",)
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1000
SOLVER:
  WARMUP_ITERS: 100
  STEPS: (11000, 11600)
  MAX_ITER: 12000
TEST:
  IMS_PER_BATCH: 8
