_BASE_: "../e2e_mask_rcnn_R_50_DC5_1x.yaml"
MODEL:
  WEIGHT: "/mnt/vol/gfsai-bistro-east/ai-group/bistro/gpu/kaiminghe/20181201/fb/DBG_e2e_mask_rcnn_R-50-C5_baseline_1x_im1.21_59_04.k8tUTZ93/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl"
DATASETS:
  TEST: ("coco_2014_minival_100",)
TEST:
  IMS_PER_BATCH: 4  # ok for 2 GPUs each with 12GB memory
  EXPECTED_RESULTS: [["bbox", "AP", 45.3080, 0.01], ["segm", "AP", 40.1749, 0.01]]
  # Expected results for coco_2014_minival:
  # EXPECTED_RESULTS: [["bbox", "AP", 37.4847, 0.01], ["segm", "AP", 33.3929, 0.01]]
