_BASE_: "../e2e_mask_rcnn_R_50_DC5_1x.yaml"
MODEL:
  WEIGHT: "catalog://Detectron2/e2e_mask_rcnn_R_50_DC5_1x/111802619/model_final_74048812947983ad784f8a3ccff02f6a.pkl"
DATASETS:
  TEST: ("coco_2014_minival_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 46.50, 0.02], ["segm", "AP", 40.54, 0.02]]
