_BASE_: "../fast_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
DATASETS:
  TRAIN: ("coco_2017_val_100",)
  PROPOSAL_FILES_TRAIN: ("detectron2://rpn_R_50_FPN_1x_inference/113323222/output/inference/coco_2017_val/box_proposals_ce43fe07beb4ef26197ee9478ab02d39.pkl",)
  TEST: ("coco_2017_val_100",)
  PROPOSAL_FILES_TEST: ("detectron2://rpn_R_50_FPN_1x_inference/113323222/output/inference/coco_2017_val/box_proposals_ce43fe07beb4ef26197ee9478ab02d39.pkl",)
SOLVER:
  BASE_LR: 0.02
  STEPS: (30,)
  MAX_ITER: 40
