_BASE_: "../fast_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHT: "catalog://Detectron2/fast_rcnn_R_50_FPN_1x/111812509/model_final_6f22b6e06cb67f3bae138e6dd8692fa7.pkl"
DATASETS:
  TEST: ("coco_2014_minival_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 44.04, 0.02]]
