_BASE_: "../fast_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
DATASETS:
  TRAIN: ("coco_2014_minival_100",)
  PROPOSAL_FILES_TRAIN: ("https://dl.fbaipublicfiles.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/test/coco_2014_minival/generalized_rcnn/rpn_proposals.pkl",)
  TEST: ("coco_2014_minival_100",)
  PROPOSAL_FILES_TEST: ("https://dl.fbaipublicfiles.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/test/coco_2014_minival/generalized_rcnn/rpn_proposals.pkl",)
SOLVER:
  BASE_LR: 0.02
  STEPS: (30,)
  MAX_ITER: 40
