_BASE_: "../COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x/137261548/model_final_04e291.pkl"
DATASETS:
  TEST: ("keypoints_coco_2017_val_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 51.60, 0.02], ["keypoints", "AP", 65.67, 0.02]]
