_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x/137259246/model_final_9243eb.pkl"
DATASETS:
  TEST: ("coco_2017_val_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 45.81, 0.02], ["segm", "AP", 40.17, 0.02]]
