_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHT: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137260431/model_final_a54504.pkl"
DATASETS:
  TEST: ("coco_2017_val_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 45.54, 0.02], ["segm", "AP",  42.06, 0.02]]
  # expected results do not use test-time augmentation. TTA results are not verified.
  AUG_ON: True
  AUG_MIN_SIZES: (400, 500)  # to save some time
