_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_DC5_1x.yaml"
MODEL:
  WEIGHT: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_DC5_1x/137260150/model_final_4f86c3.pkl"
DATASETS:
  TEST: ("coco_2017_val_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 47.23, 0.02], ["segm", "AP", 41.58, 0.02]]
