_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHT: "detectron2://e2e_mask_rcnn_R_50_FPN_1x/111801949/model_final_05dc3b6ea7b1da199fafd3b58defdaae.pkl"
  ROI_BOX_HEAD:
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlign"
  ROI_MASK_HEAD:
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlign"
DATASETS:
  TEST: ("coco_2017_val_100",)
TEST:
  # expected results do not use test-time augmentation. TTA results are not verified.
  EXPECTED_RESULTS: [["bbox", "AP", 43.51, 0.02], ["segm", "AP",  40.46, 0.02]]
  AUG_ON: True
  AUG_MIN_SIZES: (400, 500)  # to save some time
