_BASE_: "../Base-FPN.yaml"
INPUT:
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]  # Used to train this model
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  WEIGHT: "/mnt/vol/gfsai-bistro-east/ai-group/bistro/gpu/lyttonhao/panoptic_R_50_FPN_coco_1x_remove_bg_weights/model_final_update_bg.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TEST: ("coco_2017_val_100_panoptic",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 44.12, 0.02], ["segm", "AP", 41.48, 0.02], ["sem_seg", "mIoU", 40.00, 0.02]]  # noqa
