_BASE_: "../Base-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  PANOPTIC:
    SEMANTIC_LOSS_SCALE: 0.5
DATASETS:
  TRAIN: ("coco_2017_val_panoptic",)
  TEST: ("coco_2017_val_panoptic",)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  STEPS: (5500,)
  MAX_ITER: 7000
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 45.3, 0.7], ["segm", "AP", 38.6, 0.7], ["sem_seg", "mIoU", 63.5, 0.9]]
