_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  WEIGHTS: "detectron2://panoptic_R_50_FPN_1x/111802095/model_final_b5e6e676227baeca42cc501b7221ec3a.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlign"
  ROI_MASK_HEAD:
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlign"
DATASETS:
  TEST: ("coco_2017_val_100_panoptic_separated",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 46.34, 0.02], ["segm", "AP", 44.12, 0.02], ["sem_seg", "mIoU", 40.41, 0.02]]  # noqa
