_BASE_: "../COCO-Detection/rpn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHT: "detectron2://rpn_R_50_FPN_1x/111802748/model_final_0f534777b6b57e1d5e99e5bed6db6f94.pkl"
DATASETS:
  TEST: ("coco_2017_val_100",)
TEST:
  EXPECTED_RESULTS: [["box_proposals", "AR@1000", 59.51, 0.02]]
