_BASE_: "../rpn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
DATASETS:
  TRAIN: ("coco_2017_val_100",)
  TEST: ("coco_2017_val_100",)
SOLVER:
  BASE_LR: 0.02
  STEPS: (30,)
  MAX_ITER: 40
