_BASE_: "../Base-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentator"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_2017_val_panoptic_stuffonly",)
  TEST: ("coco_2017_val_panoptic_stuffonly",)
SOLVER:
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 300
  STEPS: (5500, 5800)
  MAX_ITER: 6000
TEST:
  EXPECTED_RESULTS: [["sem_seg", "mIoU", 60.8, 1.0], ["sem_seg", "mACC", 68.8, 0.7]]
