_BASE_: "../Base-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentator"
  WEIGHT: "catalog://Detectron2/semantic_R_50_FPN_1x/111802073/model_final_c18079783c55a94968edc28b7101c5f0.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TEST: ("coco_2017_val_100_panoptic_stuffonly",)
TEST:
  EXPECTED_RESULTS: [["semantic_seg", "mIoU", 39.53, 0.02], ["semantic_seg", "mACC", 51.50, 0.02]]
