_BASE_: "../Base-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentator"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_panoptic_stuff_2017_val_100",)
  TEST: ("coco_panoptic_stuff_2017_val_100",)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (30,)
  MAX_ITER: 40
