_BASE_: "../Base-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentator"
  # f111802073
  WEIGHT: "/mnt/vol/gfsai-bistro-east/ai-group/bistro/gpu/rbg/20190430/baseline_2b13c3d25abc_rm_plus_one_final_V100/semantic_R_50_FPN_1x.yaml.20_17_08.cn31tg0o/output/model_final.pth"
  RESNETS:
    DEPTH: 50
DATASETS:
  TEST: ("coco_2017_val_100_panoptic_stuffonly",)
TEST:
  EXPECTED_RESULTS: [["semantic_seg", "mIoU", 39.53, 0.02], ["semantic_seg", "mACC", 51.50, 0.02]]
