_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHT: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    DEFORM_ON_PER_STAGE: [False, False, False, True] # on Res5
    DEFORM_MODULATED: True

