_BASE_: "../Base-FPN.yaml"
MODEL:
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # For better, more stable performance initialize from COCO
  # Create from f111801949 by:
  #   checkpoint = torch.load("/mnt/vol/gfsai-bistro-east/ai-group/bistro/gpu/rbg/20190430/baseline_2b13c3d25abc_rm_plus_one_final_V100/e2e_mask_rcnn_R_50_FPN_1x.yaml.20_16_11.MWImpr5Z/output/model_final.pth")
  #   new_checkpoint = {"model": checkpoint["model"], "cfg": checkpoint["cfg"]}
  #   torch.save(new_checkpoint, "/path/to/model_final_weights_only.pth")
  # to remove optimizer, scheduler, and iteration data.
  WEIGHT: "/mnt/vol/gfsai-bistro-east/ai-group/bistro/gpu/rbg/20190430/baseline_2b13c3d25abc_rm_plus_one_final_V100/e2e_mask_rcnn_R_50_FPN_1x.yaml.20_16_11.MWImpr5Z/output/model_final_weights_only.pth"
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 8
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
DATASETS:
  # Uncomment to use coco style annotations:
  # TRAIN: ("cityscapes_fine_instanceonly_seg_train_cocostyle",)
  TRAIN: ("cityscapes_fine_instanceonly_seg_train",)

  # Evaluate with both coco API and cityscapes API
  TEST: ("cityscapes_fine_instanceonly_seg_val", "cityscapes_fine_instanceonly_seg_val_cocostyle")
SOLVER:
  BASE_LR: 0.01
  STEPS: (18000,)
  MAX_ITER: 24000
  IMS_PER_BATCH: 8
TEST:
  EVAL_PERIOD: 8000
