MODEL:
  META_ARCHITECTURE: "MaskTrackRCNN"
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137260431/model_final_a54504.pkl"
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TEST: 200  # Per FPN level
    POST_NMS_TOPK_TEST: 200
    PRE_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TRAIN: 1000
    SMOOTH_L1_BETA: 0.11
  ROI_HEADS:
    NAME: "MaskTrackROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 40
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
DATASETS:
  TRAIN: ("ytvis_2019_train",)
  TEST: ("ytvis_2019_valid",)
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.005
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
  STEPS: (8000, 9600)
  MAX_ITER: 12000
  WARMUP_FACTOR: 0.33
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1500
INPUT:
  MASK_FORMAT: "bitmask"
  MIN_SIZE_TRAIN: (360,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 360
  MAX_SIZE_TEST: 640
VERSION: 2
