MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    USE_FPN: True
    OUT_CHANNELS: 256
  RESNETS:
    RETURN_FEATURES: ["res2", "res3", "res4", "res5"]
  RPN:
    USE_FPN: True
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
  ROI_BOX_HEAD:
    NAME: "FastRCNN2MLPHead"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  ROI_MASK_HEAD:
    NAME: "MaskRCNN4ConvUpsampleHead"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
