_BASE_: "Base-RCNN-FPN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DENSEPOSE_ON: True
  ROI_HEADS:
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseV1ConvXHead"
DATASETS:
  TRAIN: ("densepose_coco_2014_train", "densepose_coco_2014_valminusminival")
  TEST: ("densepose_coco_2014_minival",)
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 24
  WARMUP_FACTOR: 0.1

