_BASE_: "Base-FPN.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/FAIR/R-50-GN"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    NORM: "GN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "GN"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "GN"
  ROI_MASK_HEAD:
    NORM: "GN"
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
