_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  MASK_ON: False
  LOAD_PROPOSALS: True
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
DATASETS:
  TRAIN: ("coco_2017_train",)
  PROPOSAL_FILES_TRAIN: ("detectron2://rpn_R_50_FPN_1x_inference/113323222/output/inference/coco_2017_train/box_proposals_030afcc26519628409442b6c9657c510.pkl", )
  TEST: ("coco_2017_val",)
  PROPOSAL_FILES_TEST: ("detectron2://rpn_R_50_FPN_1x_inference/113323222/output/inference/coco_2017_val/box_proposals_ce43fe07beb4ef26197ee9478ab02d39.pkl", )
DATALOADER:
  NUM_WORKERS: 2
