_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
      POST_NMS_TOPK_TEST: 2000
SOLVER:
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
