void ROIPooling_updateOutput(
    THCState *state,
	THCudaTensor *input,
	THCudaTensor *rois,
	int pooledHeight,
	int pooledWidth,
	float spatialScale,
	THCudaTensor *output,
	THCudaIntTensor *argmaxes);
